name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      - name: Установить Allure
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Запустить тесты Playwright
        run: |
          mkdir -p allure-results
          pytest tests/test_ultimateqa_ui_po.py tests/test_ultimateqa_ui.py --alluredir=allure-results --env=qa


      - name: Генерация отчета Allure
        run: |
          curl -o allure.zip -L https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.19.0/allure-commandline-2.19.0.zip
          unzip allure.zip -d /opt/
          export PATH=$PATH:/opt/allure-2.19.0/bin
          allure generate allure-results --clean -o allure-report

          
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report
          path: ./allure-report

      - name: Развертывание отчета Allure на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
